# Generated by Django 4.1.7 on 2023-03-25 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_owner_name', models.CharField(max_length=50)),
                ('developer_name', models.CharField(max_length=50)),
                ('scrum_master_name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('methodology', models.CharField(max_length=50)),
            ],
        ),
    ]
